version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0b26aadbo4c73cbj80g-a.oregon-postgres.render.com/selin
      SPRING_DATASOURCE_USERNAME: selin
      SPRING_DATASOURCE_PASSWORD: m5xDd3TjUklMf0tiIxmRPv5EOHhui0eh
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
